#!/usr/bin/env bash
set -euo pipefail

# 下载 ExifTool 的完整 Perl 分发包，并整理到 third_party/exiftool。
# 支持自定义下载地址：
#   EXIFTOOL_TAR_URL="https://exiftool.org/Image-ExifTool-xx.xx.tar.gz" ./scripts/prepare_exiftool.sh

# Resolve project root whether this script is run from project root or scripts/.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "${SCRIPT_DIR}/CMakeLists.txt" ]]; then
  ROOT_DIR="${SCRIPT_DIR}"
elif [[ -f "${SCRIPT_DIR}/../CMakeLists.txt" ]]; then
  ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
else
  echo "无法定位项目根目录：未在脚本目录或其上级目录找到 CMakeLists.txt" >&2
  exit 1
fi
THIRD_PARTY_DIR="${ROOT_DIR}/third_party"
TARGET_DIR="${THIRD_PARTY_DIR}/exiftool"
CACHE_DIR="${THIRD_PARTY_DIR}/.cache"
HOME_PAGE="https://exiftool.org/"

mkdir -p "${TARGET_DIR}" "${CACHE_DIR}"

if [[ -z "${EXIFTOOL_TAR_URL:-}" ]]; then
  echo "正在从 exiftool.org 获取最新源码包地址..."
  HOME_HTML="${CACHE_DIR}/exiftool_home.html"
  curl -L --fail --retry 3 --connect-timeout 20 "${HOME_PAGE}" -o "${HOME_HTML}"

  TARBALL_NAME="$(perl -0777 -ne '
    while (/Image-ExifTool-([0-9]+(?:\.[0-9]+)*)\.tar\.gz/g) { $v{$1}=1 }
    END {
      @versions = sort {
        @a = split(/\./, $a); @b = split(/\./, $b);
        for ($i=0; $i<@a || $i<@b; $i++) {
          $cmp = (($a[$i] // 0) <=> ($b[$i] // 0));
          last if $cmp;
        }
        $cmp;
      } keys %v;
      die "no exiftool tarball found\n" unless @versions;
      print "Image-ExifTool-$versions[-1].tar.gz";
    }
  ' "${HOME_HTML}")"
  EXIFTOOL_TAR_URL="${HOME_PAGE}${TARBALL_NAME}"
fi

TARBALL_PATH="${CACHE_DIR}/$(basename "${EXIFTOOL_TAR_URL}")"
EXTRACT_DIR="${CACHE_DIR}/extract"

echo "下载 ExifTool：${EXIFTOOL_TAR_URL}"
curl -L --fail --retry 3 --connect-timeout 30 "${EXIFTOOL_TAR_URL}" -o "${TARBALL_PATH}"

rm -rf "${EXTRACT_DIR}"
mkdir -p "${EXTRACT_DIR}"
tar -xzf "${TARBALL_PATH}" -C "${EXTRACT_DIR}"

SRC_DIR="$(find "${EXTRACT_DIR}" -maxdepth 1 -type d -name 'Image-ExifTool-*' | head -n 1)"
if [[ -z "${SRC_DIR}" ]]; then
  echo "未找到解压后的 Image-ExifTool-* 目录。" >&2
  exit 1
fi

rm -rf "${TARGET_DIR}"
mkdir -p "${TARGET_DIR}"
cp "${SRC_DIR}/exiftool" "${TARGET_DIR}/exiftool"
cp -R "${SRC_DIR}/lib" "${TARGET_DIR}/lib"
chmod +x "${TARGET_DIR}/exiftool"

VERSION="$(${TARGET_DIR}/exiftool -ver || true)"
cat > "${TARGET_DIR}/README.md" <<README_INNER
# Bundled ExifTool

This directory is generated by scripts/prepare_exiftool.sh.

Bundled version: ${VERSION}
Source URL: ${EXIFTOOL_TAR_URL}

The application bundles ExifTool inside:
FileMetaCleaner.app/Contents/Resources/exiftool/

This allows end users to run the app without installing Homebrew or ExifTool separately.
README_INNER

echo "ExifTool 已准备完成：${TARGET_DIR}"
ls -la "${TARGET_DIR}"
